### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by asharanjith** [asharanjith/Food-Recipes-App#21]
Hi, 
We are a team of two
@asharanjith 
@AhmadiGu 

Please [click here](https://github.com/users/asharanjith/projects/4) to see the project we have created.

**Comment by Owusu-Desmond** [comment]
Hi @asharanjith and @AhmadiGu , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

<img src="https://media3.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
📌 Descriptive Issue✅
📌 Great working on the setup of the project Kanban board ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] You have set up the board nicely and have cards assigned to team members :+1: :100:  However, Each project requirement should have at least one card in the Kanban board but now the requirement "**_Create a navigation menu that allows users to open all of the pages you created_**" does not have a corresponding card in the board so make sure that you create an additional card with this requirement :+1:  and submit this same issue link for review :pray: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Owusu-Desmond** [comment]
Hi @asharanjith and @AhmadiGu , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

<img src="https://media3.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
📌 Descriptive Issue✅
📌 Great working on the setup of the project Kanban board ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] You have set up the board nicely and have cards assigned to team members :+1: :100:  However, Each project requirement should have at least one card in the Kanban board but now the requirement "**_Create a navigation menu that allows users to open all of the pages you created_**" does not have a corresponding card in the board so make sure that you create an additional card with this requirement :+1:  and submit this same issue link for review :pray: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
